### PR TITLE
Global chart upgrade

### PR DESCRIPTION
**Pull request by NismoFur**
### Problem:
By default we can not set config for OIDC auth, optional basic authentication, external IP address for WG NLB service & PostgreSQL config.

### Changes:
1. Added WireGuard, Web and PostgreSQL config secret names
2. Added conditions for local admins username and password
3. Added OIDC config
4. Added initContainers for merging OIDC config with main config
5. Basic auth now is optional
6. Added extraVolumes for importing merged config
7. Added PostgreSQL config
8. Added externalIPs for udp WG service
9.  Added workflow for publishing

### CODE REVIEW

**Comment by DasSkelett** [comment]
Hey @NismoFur and @Strangerxxx, thanks a lot!
It looks like you've put quite some effort into maintaining the chart. Would you like to "officially" take over maintenance of it, i.e. get push access to this repository?
I for one can't meaningfully review Helm chart changes, so I'd "just press merge" anyway. So we might as well cut out the middleman.

**Comment by Strangerxxx** [comment]
Hello, @DasSkelett!

Thank you for merging this PR as it is! :)
We're working together with @NismoFur at @sharekey, so it would be nice to maintain it based on our company and community needs. 
Could we get access for the repository for our company (or single group of it)?
Or it can only be a personal access?

BTW, I'm going to create Pull Request with some changes for the main repository soon :)

Have a good day!

**Comment by DasSkelett** [comment]
It doesn't look like GitHub allows adding entire organizations as collaborators, so it looks like we'll have to add you one-by-one. But maybe @awlx knows more (she'll have to do the adding anyway).
The alternative would be using the repository from your organization and pointing to it in all our docs and the README.

**Comment by awlx** [comment]
I invited the organisation to the wg-access-helm team. I think that should work @DasSkelett
Screenshot 2022-06-17 at 15 56 37

**Comment by awlx** [comment]
@NismoFur @Strangerxxx I added you both to the team related to this Repo :). Thank you for contributing!

**Pull request merged**
